import 'package:paytack/routes/app_screens.dart';

List<Map<String, dynamic>> data = [
  {
    "title": '1. INTRODUCTION',
    "description":
        "We at PayTack AB focus on uncovering a secure check-in and payment intermediary for businesses and customers in various industries. Our technology is based on smart cloud solutions compatible with smart phones and tablets that facilitate businesses to connect with their customers in a sustainable, plastic-free way. These General Terms and Conditions (“Terms”) govern your access to, and use of, the Services provided by PayTack AB. When you access or use the Services, you agree to all of these Terms. Your use of our Services is also subject to our Privacy Policy. Privacy is very important to us at PayTack. We ask that you read these Terms and the Privacy Policy carefully. If you have got questions after reading these Terms and the Privacy Policy in its entirety, please feel free to contact us at support@paytack.dk The Services are provided by Paytack AB (559182-3181), a duly registered Swedish company with corporate domicile Anckargripsgatan 3, SE-211 19 Malmö, Sweden (“PayTack”, “us”, “our” or “we”).",
  },
  {
    "title": '3. PROVISION OF SERVICES',
    "description":
        "PayTack is a service for secure check-in and payment intermediary between the User, in his or her capacity as a consumer, and a Merchant. Thus, PayTack does not act as a payment service provider and your Account is not a payment account. 3.2 When purchasing any product or service from a Merchant, PayTack is not liable for performance of said Merchant’s obligation. You are aware, acknowledge and agree that any purchase is made in accordance with said Merchant’s terms and conditions.",
  },
  {
    "title": '4. LEGAL RELATIONSHIP',
    "description":
        "4.1 You must be a natural person of at least 18 years of age to agree to these Terms and use the Services. Use of certain Services may have further eligibility requirements that will need to be verified prior to you using such Services. Any use of the Services by an unregistered person is not authorized. 4.2 You specifically agree to use the Services only for your own personal use as a consumer and no other purpose such as, but not limited to, the use of any other person’s personal data. 4.3 The access, or attempted access, of the Services by another person than the User is not permitted under these Terms. User is not permitted to authorize another person access to User’s Account. 4.4 You may register one (1) Account. If you attempt to open more than one (1) account, such additional account(s) may be suspended or terminated. 4.5 We may also not provide all or some of our Services to certain persons or regions if, for example, in doing so, we would not be in compliance with the laws relating to our Services in such jurisdictions.",
  },
  {
    "title": '5. YOUR USE OF THE SERVICES',
    "description":
        "5.1 You agree to use the Services only for purposes that are permitted by (a) these Terms, (b) any applicable guidelines or policies provided by PayTack (including through the Services) and (c) law, regulation or generally accepted practices or guidelines in the relevant jurisdictions (including any Data Protection Laws or associated laws regarding the export of data or software to and from Sweden, the European Union or other relevant countries). 5.2 You agree that PayTack may close, suspend, or limit your access to your Account and the Services (or longer if pursuant to a court order or other legal process) if you violate these Terms or any other agreement you have entered into with PayTack, or as may be otherwise specified in these Terms. 5.3 You agree that PayTack reserve the right to change, suspend, or discontinue any aspect of the Services at any time, including hours of operation or availability of any feature, without notice and without liability. We may decline to process any purchase without prior notice. Suspension of your use of any of the Services will not affect your rights and obligations pursuant to these Terms.",
  },
  {
    "title": '6. YOUR PRIVACY AND PERSONAL DATA',
    "description":
        "To assist you in understanding these Terms please note the Definitions hereunder: • Account: means an account registered by a User. • Affiliates: means subsidiaries, franchisees and other legal entities with which PayTack has binding contracts regarding the provision of the Services, including companies contributing in the creation and/or provision of the Services. • Application: means the smartphone application provided by PayTack available on iOS Appstore, Google Play or any other market authorized by PayTack. • Merchant: means any third-party service provider whose services User can subscribe to and enter into a separate agreement with concerning the purchase of products or services. • Consent: means the consent given by a user for the processing of his or her data in compliance with Data Protection Laws. • Data Protection Laws: means the General Data Protection Regulation (EU) 2016/679 of the European Parliament and the Council of 27 April 2016 on the protection of natural persons regarding the processing of personal data and on the free movement of such data and repealing the Directive (the “GDPR”), National Data Protection Laws, and any applicable laws and/or regulations implementing the GDPR. • Facial Recognition: means the processing of biometric data relating to the User face for the purpose of uniquely identifying the User. • Personal Data: means any information relating to an identified or identifiable natural person and protected as personal data under applicable Data Protection Laws. • Services: defined in Section 3. • User: means a natural person in his or her capacity as a consumer.",
  },
  {
    "title": '7. SECURITY',
    "description":
        "7.1 You specifically agree not to (a) access (or attempt to access) the Services by any means other than through the interface of the Application, unless you have been specifically allowed to do so in a separate written agreement with PayTack; (b) access (or attempt to access) the Services through any automated means (including, but not limited to, use of scripts, robots, agents or web crawlers); (c) interfere with or disrupt the Services, or servers or networks connected to the Services; or (d) take any other actions that can be damaging in relation to PayTack or our Affiliates, the Services or third parties. 7.2 You are responsible for maintaining the confidentiality and security of any and all Account names, user IDs, passwords, personal identification numbers, and mobile unlock codes that you can use to access the Services. You agree to notify PayTack immediately if you become aware of any unauthorized use of the Services or any other breach of security regarding the Services at support@paytack.dk. PayTack will not be liable for any loss or damage arising from your failure to protect your Account. 7.3 You agree that if you become aware of any unauthorized charge occurring through your Account, you should contact PayTack customer support as soon as possible via phone or via e-mail. 7.4 You agree that we may, at our sole discretion, delay purchases or withdrawals if we believe the transaction is suspicious, may involve fraud, violates applicable laws or violates these Terms.",
  },
  {
    "title": '8. PROPERTY RIGHTS',
    "description":
        "8.1 You are aware, acknowledge and agree that PayTack, its Affiliates and/or service providers owns all legal right, title and interest in and to the Services, including any intellectual property rights which subsist therein (whether those rights happen to be registered or not, and wherever in the world those rights may exist) and that you do not acquire any right, title or interest in or to the Services unless expressly set forth in these Terms. 8.2 Nothing in these Terms gives you a right to use any of PayTack’s trade names, trademarks, service marks, logos, domain names or other distinctive brand features, unless otherwise agreed in writing with PayTack.",
  },
  {
    "title": '9. EXTERNAL LINKS',
    "description":
        "9.1 The Services may include hyperlinks to web sites, content or resources provided by Merchant. PayTack may have no control over any web sites, content or resources which are not provided by PayTack. 9.2 You are aware, acknowledge and agree that PayTack is not responsible for the availability of any external sites (including any provided by Merchant) content or resources, and does not endorse any advertising, products or other materials on or available from such web sites, content or resources and that PayTack is not liable for any loss or damage which may be incurred by you as a result of the availability of those external sites, content or resources, or as a result of any reliance placed by you on the completeness, accuracy or existence of any advertising, products, information or other materials on, or available from, such web sites, content or resources.",
  },
  {
    "title": '10. GENERAL PROVISIONS',
    "description":
        "10.1 You are aware, acknowledge and agree that these Terms constitutes the entire agreement and understanding between you and PayTack relating to the subject matter hereof (but excluding any services which PayTack may provide to you under a separate written agreement) and supersedes all written or oral commitments, undertakings and agreements which have preceded these Terms. 10.2 You are aware, acknowledge and agree that any amendment, change or modification of these Terms, other than as set out above, may only be made by a written agreement between the parties. 10.3 You are aware, acknowledge and agree that in no event shall any delay, failure or omission of a Party in enforcing, exercising or pursuing any right, claim or remedy under these Terms be deemed as a waiver thereof, unless such right, claim or remedy has been expressly waived in writing. 10.4 If any court of law, having the jurisdiction to decide on this matter, finds that any provision of these Terms (or the application thereof) shall be declared or deemed void, invalid or unenforceable in whole or in part for any reason, that provision shall be enforced to the maximum extent permissible so as to affect the intent of these Terms and the remaining provisions of these Terms shall continue in full force and effect. 10.5 The English language shall be the governing language in your relationship with PayTack, unless otherwise required by mandatory national law. 10.6 The User shall not be entitled to assign its rights and/or obligations under these Terms without PayTack’s prior written approval. PayTack shall be entitled to assign its rights and/or obligations under these Terms without the prior written approval of the User.",
  },
  {
    "title": '11. INDEMNITY',
    "description":
        "11.1 You agree to hold harmless and indemnify PayTack, its Affiliates and each of their respective directors, officers, agents, and employees from and against any third party claim arising from or in any way related to your use of the Services, violation of these Terms or any other actions connected with your use of the Services, including any liability or expense arising from all claims, losses, damages (actual and consequential), suits, judgments, litigation costs and attorneys' fees, of every kind and nature. In such a case, PayTack will provide you with written notice of such claim, suit or action. PayTack shall have the right to participate, at its own expense, in the defense of any claim. You shall not agree to any settlement of any claim as set out above without the prior written consent of PayTack.",
  },
  {
    "title": '12. LIMITATION OF LIABILITY',
    "description":
        "12.1 You are aware, acknowledge and agree that PayTack, Affiliates, service providers and their respective officers, directors, agents, joint venturers, employees, and representatives will not be liable for any indirect, incidental, special, consequential, exemplary damages, or damages for loss of profits including but not limited to, damages for loss of goodwill, use, data, or other intangible losses (even if PayTack has been advised of the possibility of such damages), whether based on contract, tort, negligence, strict liability, or otherwise, resulting from (a) the use or the inability to use the services; (b) the cost of procurement of substitute goods and services resulting from any goods, data, information, or services purchased or obtained or messages received or transactions entered into through or from the services; (c) unauthorized access to or alteration of your transmissions or data; or (d) any other matter relating to the Services. 12.2 Some jurisdictions do not allow the exclusion of certain warranties or the limitation or exclusion of liability for incidental or consequential damages. Accordingly, some of the limitations set forth above may not apply to you. If you are dissatisfied with any portion of the services or with these Terms, your sole and exclusive remedy is to discontinue use of the Services and delete your Account. 12.3 The Services are provided “as is”, “as available” and without any representation or warranty, whether express, implied, or statutory. PayTack, our Affiliates, and our respective officers, directors, agents, joint venturers, employees, and suppliers specifically disclaim any implied warranties of title, merchantability, fitness for a particular purpose or non-infringement. PayTack makes no warranty that (a) the Services will meet your requirements, (b) the Services will be uninterrupted, timely, secure, or error-free, or (c) the quality of any products, services, information, or other material purchased or obtained by you will meet your expectations.",
  },
  {
    "title": '13. GOVERNING LAW AND JURISDICTION',
    "description":
        "13.1 These Terms, and your relationship with PayTack under these Terms, shall, to the maximum extent permitted by applicable mandatory law in your jurisdiction, be governed by and construed in accordance with the substantive laws of Sweden without giving effect to the choice of law principles thereof. 13.2 Any dispute, controversy or claim arising out of or in connection with these Terms, or the breach, termination or invalidity thereof, shall be settled by a Swedish court of general jurisdiction and the Malmö District Court (Swedish: Malmö tingsrätt) shall be the court of first instance. 13.3 Notwithstanding the above, you are aware, acknowledge and agree that PayTack shall always be allowed to apply for injunctive remedies (or an equivalent type of urgent legal relief) in any jurisdiction and through any court of competent jurisdiction.",
  },
  {
    "title": '14. TERMS',
    "description":
        "14.1 PayTack may make changes to these Terms from time to time. Any changes to these Terms will be notified to you notice through our Services, or by other means, to provide you the opportunity to review the changes before they become effective. You are aware, acknowledge and agree that your continued use of the Services after the date on which these Terms have changed as set out above will constitute your acceptance of the changed Terms. If you object to any changes, you may delete your Account. 14.2 These Terms enters into force on the date you first agree to them (as set out under Section 4) and will continue in force thereafter until terminated by either you or PayTack as set out below. Upon termination of these Terms for any reason, you must immediately cease using the Services. 14.3 These Terms are terminated if you delete your Account.",
  },
];
